// Generated by tools/convert_wav.py — do not edit by hand.
//
// The sample library does NOT live inside the firmware: it sits at a fixed
// flash offset and is read through XIP. To reflash it without rebuilding:
//
//     picotool load -o 0x10080000 sample_lib.bin
//
#ifndef SAMPLE_LIB_H
#define SAMPLE_LIB_H

#include <stdbool.h>
#include <stdint.h>

#define SAMPLE_LIB_FLASH_OFFSET 0x80000u
#define SAMPLE_LIB_XIP_ADDR     0x10080000u
#define SAMPLE_LIB_MAGIC        0x4C504D53u  // 'SMPL' little-endian
#define SAMPLE_LIB_VERSION      2  // what this blob is
#define SAMPLE_LIB_VERSION_MIN  1  // oldest blob the firmware still reads
#define SAMPLE_LIB_RATE         22050
#define SAMPLE_LIB_NAME_LEN     24

// Entries per kit in a version-2 blob: entry k * SAMPLE_LIB_KIT_SIZE + s is
// the sample for slot s of kit k. Must equal NUM_SLOTS.
#define SAMPLE_LIB_KIT_SIZE     8

typedef struct {
    char     name[SAMPLE_LIB_NAME_LEN];  // NUL-padded
    uint32_t offset_bytes;               // from the start of the blob
    uint32_t length_samples;
} SampleEntry;

typedef struct {
    char        magic[4];
    uint16_t    version;
    uint16_t    count;
    uint32_t    sample_rate;
    uint32_t    total_bytes;
    SampleEntry entries[];
} SampleLib;

_Static_assert(sizeof(SampleEntry) == 32, "SampleEntry layout does not match the blob");
_Static_assert(sizeof(SampleLib) == 16, "SampleLib layout does not match the blob");

// XIP pointer to the library. Only valid once sample_lib_valid() says so.
#define SAMPLE_LIB ((const SampleLib *)SAMPLE_LIB_XIP_ADDR)

// Unprogrammed flash reads back as 0xFF: without this check the firmware would
// read garbage as a TOC and dereference random offsets.
static inline bool sample_lib_valid(const SampleLib *lib) {
    return lib->magic[0] == 'S' && lib->magic[1] == 'M' &&
           lib->magic[2] == 'P' && lib->magic[3] == 'L' &&
           lib->version >= SAMPLE_LIB_VERSION_MIN &&
           lib->version <= SAMPLE_LIB_VERSION && lib->count > 0;
}

// Whether the entries are grouped in kits. A flat version-1 blob is still
// playable, it just has no kit to load: the firmware falls back to filling the
// slots by position.
static inline bool sample_lib_is_kits(const SampleLib *lib) {
    return lib->version >= 2 && lib->count >= SAMPLE_LIB_KIT_SIZE &&
           lib->count % SAMPLE_LIB_KIT_SIZE == 0;
}

static inline unsigned sample_lib_kit_count(const SampleLib *lib) {
    return sample_lib_is_kits(lib) ? lib->count / SAMPLE_LIB_KIT_SIZE : 0;
}

static inline const int16_t *sample_lib_data(const SampleLib *lib, unsigned i) {
    return (const int16_t *)((const uint8_t *)lib + lib->entries[i].offset_bytes);
}

#endif // SAMPLE_LIB_H
